apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dv8o
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0006-tenant/ci1t-43256-0006-app/devfile-sample-dv8o@sha256:a14812ff61b4ff29ae8d3cec14a9214e9a3e0a9c31d78e268ef8b8c9f7239dd7
        name: my-nodejs
        resources: {}
status: {}
